### ISSUE TITLE
Question about inverse propensity score loss

### ISSUE THREAD

**Issue by shi-ang** [RyanWangZf/SurvTRACE#1]
Hi Zifeng,

I read your paper on Arxiv and got interested in the inverse propensity score loss that you implemented for debiasing the competing events. However, I still have some questions about this and hope you can help me with them.

I can see from the paper that IPS-weighting, ![equation](https://latex.codecogs.com/gif.latex?\pi_{ik}&space;=&space;Pr(e_i&space;=&space;k&space;|&space;\phi,&space;\boldsymbol{x})), is trained to estimate the true distribution of the competing events. Based on your equation 20, ![equation](https://latex.codecogs.com/gif.latex?\pi_{ik}\triangleq&space;\sigma(\boldsymbol{w}^T\boldsymbol{x}_i&plus;\beta)), this IPS weighting is seemed to be obtained from scratch using a different model, not a downstream model after the latent representation ![equation](https://latex.codecogs.com/gif.latex?t_{SR}).

However, I didn't find this implementation in this repo. Can you let me know in which part did you implement this IPS loss? Sorry if the questions are naive or due to my carelessness. I'm looking forward to hearing from you.

Best,
Shiang

**Comment by RyanWangZf** [comment]
Hi there, this weight can be obtained by an additional logistic regression model. The input x can be raw features of patients. So no need of using learned representations. It has been proved that too precise inverse propensity weight can induce high variance (https://arxiv.org/pdf/1602.05352.pdf), so we should not use a too strong model for estimating IPS.

The current repo does not include it and the multi-task learning part. I will update the implementation later. Thanks for your attention!

**Comment by shi-ang** [comment]
Thanks for your reply! Looking forward to your future updates.
