### ISSUE TITLE
Fail to install the enviroment

### ISSUE THREAD

**Issue by Dan-121** [RyanWangZf/SurvTRACE#3]
Hi,Zifeng:
Your work is very good and I really want to use this method .
But i meet some problem at the first step:

conda env create --name survtrace --file=survtrace.yml

Here is the problem

- [ ] Collecting package metadata (repodata.json): done
- [ ] Solving environment: failed
- [ ] ResolvePackageNotFound: 
- [ ]   - vs2015_runtime==14.27.29016=h5e58377_2
- [ ]   - m2w64-gmp==6.1.0=2
- [ ]   - cvxopt==1.2.5=py36h542453d_0
- [ ]   - glpk==4.65=hdc00fd2_2
- [ ]   - multiprocess==0.70.11.1=py36hf4a77e7_0
- [ ]   - mkl_fft==1.3.0=py36h46781fe_0
- [ ]   - icc_rt==2019.0.0=h0cc432a_1
- [ ]   - setuptools==58.0.4=py36haa95532_0
- [ ]   - libcblas==3.9.0=5_hd5c7e75_netlib
- [ ]   - fastcache==1.1.0=py36he774522_0
- [ ]   - sqlite==3.36.0=h2bbff1b_0
- [ ]   - wincertstore==0.2=py36h7fe50ca_0
- [ ]   - certifi==2021.5.30=py36ha15d459_0
- [ ]   - vc==14.2=h21ff451_1
- [ ]   - python==3.6.13=h3758d61_0
- [ ]   - scikit-learn==0.22.1=py36h7208079_1
- [ ]   - numexpr==2.7.3=py36hcbcaa1e_0
- [ ]   - scikit-survival==0.14.0=py36he350917_0
- [ ]   - scs==2.1.2=py36haa4650d_0
- [ ]   - ecos==2.0.7.post1=py36haa4650d_3
- [ ]   - msys2-conda-epoch==20160418=1
- [ ]   - scipy==1.5.2=py36h9439919_0
- [ ]   - mkl_random==1.1.1=py36h47e9c7a_0
- [ ]   - numpy-base==1.19.2=py36ha3acd2a_0
- [ ]   - m2w64-gcc-libs==5.3.0=7
- [ ]   - cvxpy-base==1.0.31=py36h6538335_0
- [ ]   - intel-openmp==2021.3.0=haa95532_3372
- [ ]   - m2w64-libwinpthread-git==5.0.0.4634.697f757=2
- [ ]   - libblas==3.9.0=1_h8933c1f_netlib
- [ ]   - mkl-service==2.3.0=py36h196d8e1_0
- [ ]   - pandas==1.1.5=py36hd77b12b_0
- [ ]   - osqp==0.5.0=py36haa4650d_3
- [ ]   - m2w64-gcc-libgfortran==5.3.0=6
- [ ]   - pip==21.0.1=py36haa95532_0
- [ ]   - m2w64-gcc-libs-core==5.3.0=7

And my compter is _Architecture:                  

- [ ]  x86_64
- [ ] CPU op-mode(s):                  32-bit, 64-bit
- [ ] Byte Order:                      Little Endian
- [ ] Address sizes:                   46 bits physical, 48 bits virtual
- [ ] CPU(s):                          32
- [ ] On-line CPU(s) list:             0-31
- [ ] Thread(s) per core:              2
- [ ] Core(s) per socket:              16
- [ ] Socket(s):                       1
- [ ] NUMA node(s):                    1
- [ ] Vendor ID:                       GenuineIntel
- [ ] CPU family:                      6
- [ ] Model:                           85
- [ ] Model name:                      Intel(R) Xeon(R) Gold 6246R CPU @ 3.40GHz
- [ ] Stepping:                        7
- [ ] CPU MHz:                         3400.000
- [ ] CPU max MHz:                     4100.0000
- [ ] CPU min MHz:                     1200.0000
- [ ] BogoMIPS:                        6800.00
- [ ] Virtualization:                  VT-x
- [ ] L1d cache:                       512 KiB
- [ ] L1i cache:                       512 KiB
- [ ] L2 cache:                        16 MiB
- [ ] L3 cache:                        35.8 MiB
- [ ] NUMA node0 CPU(s):               0-31
- [ ] Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
- [ ] Vulnerability L1tf:              Not affected
- [ ] Vulnerability Mds:               Not affected
- [ ] Vulnerability Meltdown:          Not affected
- [ ] Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled v
- [ ]                                  ia prctl and seccomp
- [ ] Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
- [ ]                                   pointer sanitization
- [ ] Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RS
- [ ]                                  B filling
- [ ] Vulnerability Srbds:             Not affected
- [ ] Vulnerability Tsx async abort:   Mitigation; TSX disabled
- [ ] Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
- [ ]                                  r pge mca cmov pat pse36 clflush dts acpi mmx f
- [ ]                                  xsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rd
- [ ]                                  tscp lm constant_tsc art arch_perfmon pebs bts 
- [ ]                                  rep_good nopl xtopology nonstop_tsc cpuid aperf
- [ ]                                  mperf pni pclmulqdq dtes64 monitor ds_cpl vmx s
- [ ]                                  mx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid d
- [ ]                                  ca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadli
- [ ]                                  ne_timer aes xsave avx f16c rdrand lahf_lm abm 
- [ ]                                  3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 inv
- [ ]                                  pcid_single intel_ppin ssbd mba ibrs ibpb stibp
- [ ]                                   ibrs_enhanced tpr_shadow vnmi flexpriority ept
- [ ]                                   vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep
- [ ]                                   bmi2 erms invpcid cqm mpx rdt_a avx512f avx512
- [ ]                                  dq rdseed adx smap clflushopt clwb intel_pt avx
- [ ]                                  512cd avx512bw avx512vl xsaveopt xsavec xgetbv1
- [ ]                                   xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm
- [ ]                                  _mbm_local dtherm ida arat pln pts hwp hwp_act_
- [ ]                                  window hwp_epp hwp_pkg_req pku ospke avx512_vnn
- [ ]                                  i md_clear flush_l1d arch_capabilities

my conda version is 4.10.3.
thanks a lot,I will be appreciated if you reply me this stupid question

**Comment by RyanWangZf** [comment]
hi, this is because you are using a linux platform (I guess) that is different from ours (windows).

I update the survtrace.yml and requirements.txt,
please try them and tell me if they work. 😊

**Comment by Dan-121** [comment]
It is so kind of you,I will have a try,thanks a lot



发自我的iPhone


------------------ Original ------------------
From: Zifeng ***@***.***&gt;
Date: Mon,Oct 18,2021 0:11 AM
To: RyanWangZf/SurvTRACE ***@***.***&gt;
Cc: Dan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [RyanWangZf/SurvTRACE] Fail to install the enviroment (Issue #3)





 
hi, this is because you are using a linux platform (I guess) that is different from ours (windows).
 
I update the survtrace.yml and requirements.txt,
 please try them and tell me if they work. 😊

**Comment by Dan-121** [comment]
Hi,when i install we package,threre is no error
But when i library them ,here is the error:
No module named 'survtrace'
and i use conda list find that there is no package named survtrace.
Looking forward your reply

**Comment by RyanWangZf** [comment]
survtrace is our module so it is not on conda list. please make sure you are under the root directory of this repo when you run the code or `import survtrace`
